language: node_js
sudo: true
dist: trusty
node_js:
  - 8
  - 10
install:
  - yarn
  - npm i -g codecov
  - travis_wait lerna bootstrap
script:
  - npm test
notifications:
  email:
    on_failure: change
after_success:
  - codecov
