const button = {
  colors: {
    primary: {
      color: (get) => get('colorScheme', 'white'),
      colorOutline: (get) => get('colorScheme', 'primary'),
      colorOutlineHover: (get) => get('colorScheme', 'white'),
      backgroundColor: (get) => get('colorScheme', 'primary'),
      backgroundColorDisabled: (get) => get('colorScheme', 'primary'),
      backgroundColorHoverFocus: (get) => get('colorScheme', 'primaryDarker'),
      backgroundColorActive: (get) => get('colorScheme', 'primaryDark'),
      borderColor: (get) => get('colorScheme', 'primary'),
      borderColorDisabled: (get) => get('colorScheme', 'primary'),
      borderColorHoverFocus: (get) => get('colorScheme', 'primaryDark'),
      borderColorActive: (get) => get('colorScheme', 'primaryDark'),
      boxShadow: (get) => get('colorScheme', 'primaryBoxShadow'),
    },
    secondary: {
      color: (get) => get('colorScheme', 'white'),
      colorOutline: (get) => get('colorScheme', 'secondary'),
      colorOutlineHover: (get) => get('colorScheme', 'white'),
      backgroundColor: (get) => get('colorScheme', 'secondary'),
      backgroundColorDisabled: (get) => get('colorScheme', 'secondary'),
      backgroundColorHoverFocus: (get) => get('colorScheme', 'secondaryDarker'),
      backgroundColorActive: (get) => get('colorScheme', 'secondary'),
      borderColor: (get) => get('colorScheme', 'secondary'),
      borderColorDisabled: (get) => get('colorScheme', 'secondary'),
      borderColorHoverFocus: (get) => get('colorScheme', 'secondaryDark'),
      borderColorActive: (get) => get('colorScheme', 'secondaryDark'),
      boxShadow: (get) => get('colorScheme', 'secondaryBoxShadow'),
    },
    success: {
      color: (get) => get('colorScheme', 'white'),
      colorOutline: (get) => get('colorScheme', 'success'),
      colorOutlineHover: (get) => get('colorScheme', 'white'),
      backgroundColor: (get) => get('colorScheme', 'success'),
      backgroundColorDisabled: (get) => get('colorScheme', 'success'),
      backgroundColorHoverFocus: (get) => get('colorScheme', 'successDarker'),
      backgroundColorActive: (get) => get('colorScheme', 'successDark'),
      borderColor: (get) => get('colorScheme', 'success'),
      borderColorDisabled: (get) => get('colorScheme', 'success'),
      borderColorHoverFocus: (get) => get('colorScheme', 'successDark'),
      borderColorActive: (get) => get('colorScheme', 'successDark'),
      boxShadow: (get) => get('colorScheme', 'successBoxShadow'),
    },
    danger: {
      color: (get) => get('colorScheme', 'white'),
      colorOutline: (get) => get('colorScheme', 'danger'),
      colorOutlineHover: (get) => get('colorScheme', 'white'),
      backgroundColor: (get) => get('colorScheme', 'danger'),
      backgroundColorDisabled: (get) => get('colorScheme', 'danger'),
      backgroundColorHoverFocus: (get) => get('colorScheme', 'dangerDarker'),
      backgroundColorActive: (get) => get('colorScheme', 'dangerDark'),
      borderColor: (get) => get('colorScheme', 'danger'),
      borderColorDisabled: (get) => get('colorScheme', 'danger'),
      borderColorHoverFocus: (get) => get('colorScheme', 'dangerDark'),
      borderColorActive: (get) => get('colorScheme', 'dangerDark'),
      boxShadow: (get) => get('colorScheme', 'dangerBoxShadow'),
    },
    warning: {
      color: (get) => get('colorScheme', 'darkerDarker'),
      colorOutline: (get) => get('colorScheme', 'warning'),
      colorOutlineHover: (get) => get('colorScheme', 'darkerDarker'),
      backgroundColor: (get) => get('colorScheme', 'warning'),
      backgroundColorDisabled: (get) => get('colorScheme', 'warning'),
      backgroundColorHoverFocus: (get) => get('colorScheme', 'warningDarker'),
      backgroundColorActive: (get) => get('colorScheme', 'warningDark'),
      borderColor: (get) => get('colorScheme', 'warning'),
      borderColorDisabled: (get) => get('colorScheme', 'warning'),
      borderColorHoverFocus: (get) => get('colorScheme', 'warningDark'),
      borderColorActive: (get) => get('colorScheme', 'warningDark'),
      boxShadow: (get) => get('colorScheme', 'warningBoxShadow'),
    },
    info: {
      color: (get) => get('colorScheme', 'white'),
      colorOutline: (get) => get('colorScheme', 'info'),
      colorOutlineHover: (get) => get('colorScheme', 'white'),
      backgroundColor: (get) => get('colorScheme', 'info'),
      backgroundColorDisabled: (get) => get('colorScheme', 'info'),
      backgroundColorHoverFocus: (get) => get('colorScheme', 'infoDarker'),
      backgroundColorActive: (get) => get('colorScheme', 'infoDark'),
      borderColor: (get) => get('colorScheme', 'info'),
      borderColorDisabled: (get) => get('colorScheme', 'info'),
      borderColorHoverFocus: (get) => get('colorScheme', 'infoDark'),
      borderColorActive: (get) => get('colorScheme', 'infoDark'),
      boxShadow: (get) => get('colorScheme', 'infoBoxShadow'),
    },
    light: {
      color: (get) => get('colorScheme', 'darkerDarker'),
      colorOutline: (get) => get('colorScheme', 'light'),
      colorOutlineHover: (get) => get('colorScheme', 'darkerDarker'),
      backgroundColor: (get) => get('colorScheme', 'light'),
      backgroundColorDisabled: (get) => get('colorScheme', 'light'),
      backgroundColorHoverFocus: (get) => get('colorScheme', 'lightDarker'),
      backgroundColorActive: (get) => get('colorScheme', 'lightDark'),
      borderColor: (get) => get('colorScheme', 'light'),
      borderColorDisabled: (get) => get('colorScheme', 'light'),
      borderColorHoverFocus: (get) => get('colorScheme', 'lightDark'),
      borderColorActive: (get) => get('colorScheme', 'lightDark'),
      boxShadow: (get) => get('colorScheme', 'lightBoxShadow'),
      toggle: {
        color: (get) => get('colorScheme', 'dark50Alpha'),
        borderColor: (get) => get('colorScheme', 'dark10Alpha'),
        colorHoverFous: (get) => get('colorScheme', 'dark50Alpha'),
        borderColorHoverFous: (get) => get('colorScheme', 'dark10Alpha'),
      },
    },
    dark: {
      color: (get) => get('colorScheme', 'white'),
      colorOutline: (get) => get('colorScheme', 'dark'),
      colorOutlineHover: (get) => get('colorScheme', 'white'),
      backgroundColor: (get) => get('colorScheme', 'dark'),
      backgroundColorDisabled: (get) => get('colorScheme', 'dark'),
      backgroundColorHoverFocus: (get) => get('colorScheme', 'darkDarker'),
      backgroundColorActive: (get) => get('colorScheme', 'darkDark'),
      borderColor: (get) => get('colorScheme', 'dark'),
      borderColorDisabled: (get) => get('colorScheme', 'dark'),
      borderColorHoverFocus: (get) => get('colorScheme', 'darkDark'),
      borderColorActive: (get) => get('colorScheme', 'darkDark'),
      boxShadow: (get) => get('colorScheme', 'darkBoxShadow'),
      toggle: {
        color: (get) => get('colorScheme', 'white50Alpha'),
        borderColor: (get) => get('colorScheme', 'white10Alpha'),
        colorHoverFous: (get) => get('colorScheme', 'white50Alpha'),
        borderColorHoverFous: (get) => get('colorScheme', 'white10Alpha'),
      },
    },
    default: (get) => get('button', 'colors', 'secondary'),
  },
  margin: {
    blockTop: '0.5rem',
    dropDownToggleLeft: '0255rem',
  },
  padding: {
    sm: '0.25rem 0.5rem',
    lg: '0.5rem 1rem',
    default: '0.375rem 0.75rem',

    splitSmRight: '0.375rem',
    splitSmLeft: '0.375rem',
    splitLgRight: '0.75rem',
    splitLgLeft: '0.75rem',
    splitDefaultRight: '0.5625rem',
    splitDefaultLeft: '0.5625rem',
  },
  fontSize: (get) => get('globals', 'fontSize'),
  border: (get) => get('globals', 'border'),
  borderRadius: (get) => get('globals', 'borderRadius'),
};

export { button };
